### ISSUE TITLE
Can your dynamic komi be used for counting the margin one side is leading in mid-game?

### ISSUE THREAD

**Issue by zhanzhenzhen** [alreadydone/lz#41]
Can your dynamic komi be used for counting the margin one side is leading in mid-game?

**Comment by alreadydone** [comment]
No without additional training (see https://github.com/gcp/leela-zero/issues/1625#issuecomment-406757746), I think. Currently the winrate isn't accurate under komi values other than 7.5 or -7.5, since the network hasn't been trained on games with such komi values; therefore conversely, if you want to determine the komi that gives a certain winrate (say 50%), that would also be inaccurate.
